import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="min-w-screen min-h-screen relative ">
        <div className="grainy absolute inset-0 -z-[100] opacity-30 "></div>
        {children}
      </body>
    </html>
  );
}
